# Generated by Django 4.0 on 2021-12-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'voivodeship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('voivodeship', models.ForeignKey(blank=True, db_column='voivodeship', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='houses_app.voivodeship')),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.FloatField(blank=True, null=True)),
                ('id_house', models.FloatField(blank=True, null=True)),
                ('laitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('rooms', models.FloatField(blank=True, null=True)),
                ('sq', models.FloatField(blank=True, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='houses_app.city')),
            ],
            options={
                'db_table': 'apartment',
                'managed': True,
            },
        ),
    ]
