# Generated by Django 4.0 on 2022-01-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voivodeship',
            options={},
        ),
    ]
